name: CI/CD Pipeline - Docker Java App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display /app content
        run: ls -la /app || ls -la /

      - name: Build Docker image
        run: docker build -t a18_gorgui_final_1288 .

      - name: Tag Docker image
        run: docker tag a18_gorgui_final_1288 gorgui/a18_gorgui_final_1288:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push gorgui/a18_gorgui_final_1288:latest
